### ISSUE TITLE
Never mind

### ISSUE THREAD

**Issue by fireYtail** [Brikwerk/nxbt#114]

**Comment by fireYtail** [comment]
To make myself clear:

I open a cmd.exe window and go to the git directory, where "vagrant_setup.py" and "Vagrantfile" are. From there, I run "vagrant up" and "vagrant ssh", and I am in the VM (green text on my left). Then it lists the device and did the checks you mentioned and it looks fine, but can't run your Python package for some reason. It downloaded a lot of stuff and took long to install the first time (up command), also I had to choose the wrong USB device in the setup or I could not proceed, but I manually fixed that later. It reads "vagrant@ubuntu2010:" both in window title and in green text (awaiting input). I don't know what to do now.

**Comment by fireYtail** [comment]
Interestingly, removing "sudo" seems to make it run, but fail for permissions (?)

```
[1] Attempting to initialize NXBT...
Failed to initialize:
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.8/site-packages/nxbt/cli.py", line 185, in test
    nx = Nxbt(debug=args.debug, log_to_file=args.logfile)
  File "/home/vagrant/.local/lib/python3.8/site-packages/nxbt/nxbt.py", line 181, in __init__
    toggle_clean_bluez(True)
  File "/home/vagrant/.local/lib/python3.8/site-packages/nxbt/bluez.py", line 131, in toggle_clean_bluez
    override_dir.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/run/systemd/system/bluetooth.service.d'
```

Note the line "[1] Attempting to initialize NXBT..."

**Comment by fireYtail** [comment]
I hope the issue is not related to my Windows 10 being in Spanish... I'm tired of stupid gits that fail one way or another because of Windows regional settings.
