### ISSUE TITLE
Cannot run "webapp" on VM on Windows 10

### ISSUE THREAD

**Issue by fireYtail** [Brikwerk/nxbt#115]
vagrant@ubuntu2010:~$ sudo nxbt webapp

Traceback (most recent call last):
  File "/usr/local/bin/nxbt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/nxbt/cli.py", line 321, in main
    from .web import start_web_app
  File "/usr/local/lib/python3.8/dist-packages/nxbt/web/__init__.py", line 1, in <module>
    from .app import start_web_app
  File "/usr/local/lib/python3.8/dist-packages/nxbt/web/app.py", line 9, in <module>
    from flask import Flask, render_template, request
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)

**Comment by fireYtail** [comment]
Thank you for your reply!

**Comment by fireYtail** [comment]
No idea, they haven't replied despite 2 months having passed.

**Comment by Dummydud3** [comment]
this was fixed in issue #121 
sorry for late reply

**Comment by fireYtail** [comment]
2 months and 5 days later you come to say that you replied to a more recently created issue than mine about the same problem, AND that you're sorry for completely ignoring my issue while replying to the other user?

Okay. It's impossible to be more idiotic than this. You earn a trophy for your intelligence and care for your software and for other people who bother reporting bugs for nothing.

Have a good day, for the next two months... Bye to you too

**Comment by fireYtail** [comment]
It only took you 2 days to tell them that you were already aware of the issue yourself, but couldn't care less so let's wait for 2 months until a few other people start complaining.

**Comment by Dummydud3** [comment]
To be fair, I only started using this app last week, and that issue was at the top of the list, with a problem that I experienced already, and I figured, “hey, I know how to fix this”, so better late then never right? 😅Sent from my iPadOn May 22, 2023, at 8:26 PM, fireYtail ***@***.***> wrote:﻿
It only took you 2 days to tell them that you were already aware of the issue yourself, but couldn't care less so let's wait for 2 months until a few other people start complaining.

**Comment by jdmagic** [comment]
> To be fair, I only started using this app last week, and that issue was at the top of the list, with a problem that I experienced already, and I figured, “hey, I know how to fix this”, so better late then never right? 😅

You do NOT owe them an apology. They sound entitled af. You didn't owe them any help in the first place. Thank you for helping with the issue that I and so many others are having. It's much appreciated, I assure you.
