### ISSUE TITLE
After pairing "Change Grip/Order" the controller instantly disconnects  "error code"

### ISSUE THREAD

**Issue by nuttaputchb** [Brikwerk/nxbt#12]
After pairing "Change Grip/Order" menu, the controller instantly disconnects 
Then show error code 

> Traceback (most recent call last):
  File "/usr/local/bin/nxbt", line 11, in <module>
    load_entry_point('nxbt', 'console_scripts', 'nxbt')()
  File "/home/m/nxbt/nxbt/cli.py", line 229, in main
    tui.start()
  File "/home/m/nxbt/nxbt/tui.py", line 308, in start
    self.mainloop(self.term)
  File "/home/m/nxbt/nxbt/tui.py", line 370, in mainloop
    self.direct_input_loop(term)
  File "/home/m/nxbt/nxbt/tui.py", line 432, in direct_input_loop
    from pynput import keyboard
  File "/usr/local/lib/python3.8/dist-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/usr/local/lib/python3.8/dist-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/usr/local/lib/python3.8/dist-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'No protocol specified\\n\'', DisplayConnectionError(':0', b'No protocol specified\n'))
Try one of the following resolutions:
Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly

Ubuntu 20.04.1
nintendo switch lite

**Comment by Brikwerk** [comment]
Hi there, thanks for you interest in NXBT.

From your error log, it looks like pynput (the library used to get keypress events) is complaining since it's not able to get keyboard input from your system. My question to you is: how are you accessing the machine running NXBT? Are you remoting into it (eg: SSH, Mosh, etc) or are you using it direct (eg: keyboard/monitor, sitting at the machine)?

My bet is that this is an issue with remote input detection. NXBT does its best to detect if you're using a remote connection (eg: SSH, Mosh, etc), however, this can be a challenging task since there's not exactly a one-size-fits-all method for all remote technologies. Remote detection needs to be done since special compensation is required for proper remote keyboard input.

**Comment by Brikwerk** [comment]
Closing issue due to lack of activity. FYI, the next update to NXBT will include a "remote_tui" option for explicitly using NXBT's TUI functionality over a remote connection.
