### ISSUE TITLE
[Windows] Cannot start virtual machine

### ISSUE THREAD

**Issue by PMCJTM** [Brikwerk/nxbt#122]
Whenever I run vagrant up I'm met with the following message and am unable to proceed

```
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/util/file_mutex.rb:27:in `delete': Permission denied @ apply2files - C:/Users/$USER/.vagrant.d/tmp/boxf6ec71ffcb361a099c52785a183f2f9db163143b.lock (Errno::EACCES)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/util/file_mutex.rb:27:in `unlock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/util/file_mutex.rb:15:in `with_lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builtin/box_add.rb:484:in `download'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builtin/box_add.rb:204:in `add_from_metadata'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builtin/box_add.rb:128:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/warden.rb:48:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builder.rb:180:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/runner.rb:101:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/runner.rb:101:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builtin/handle_box.rb:83:in `handle_box'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/warden.rb:48:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/warden.rb:48:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builder.rb:180:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/runner.rb:101:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/runner.rb:101:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/warden.rb:48:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/plugins/providers/virtualbox/action/check_virtualbox.rb:20:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/warden.rb:48:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/builder.rb:180:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/runner.rb:101:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/action/runner.rb:101:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/machine.rb:248:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/machine.rb:217:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/environment.rb:631:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/machine.rb:203:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/machine.rb:203:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'

```

**Comment by PMCJTM** [comment]
A solution was found at https://github.com/hashicorp/vagrant/issues/13157
