### ISSUE TITLE
Failes to open webui

### ISSUE THREAD

**Issue by Brisolo32** [Brikwerk/nxbt#133]
```
  nxbt ❯ sudo nxbt webapp
Traceback (most recent call last):
  File "/usr/local/bin/nxbt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/nxbt/cli.py", line 321, in main
    from .web import start_web_app
  File "/usr/local/lib/python3.10/dist-packages/nxbt/web/__init__.py", line 1, in <module>
    from .app import start_web_app
  File "/usr/local/lib/python3.10/dist-packages/nxbt/web/app.py", line 11, in <module>
    import eventlet
  File "/usr/local/lib/python3.10/dist-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/usr/local/lib/python3.10/dist-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/usr/local/lib/python3.10/dist-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/usr/local/lib/python3.10/dist-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/usr/local/lib/python3.10/dist-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/usr/local/lib/python3.10/dist-packages/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/usr/local/lib/python3.10/dist-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
  nxbt ❯ 
```

I downloaded all correct dependencies
OS: Pop!_OS 22.04

**Comment by Brikwerk** [comment]
I believe this is an issue with the current pinned version of eventlet not being compatible with Python 3.10. I'm in the process of updating dependencies for better compatibility soon. In the meantime, you could use an earlier Python version or attempt to manually install an updated version of eventlet.

Ex:
```bash
pip3 install --upgrade eventlet
```

**Comment by argonptg** [comment]
> I believe this is an issue with the current pinned version of eventlet not being compatible with Python 3.10. I'm in the process of updating dependencies for better compatibility soon. In the meantime, you could use an earlier Python version or attempt to manually install an updated version of eventlet.
> 
> Ex:
> 
> ```shell
> pip3 install --upgrade eventlet
> ```

When I tried to update the eventlet package it returned with a dependency error and it still didn't work, guess I'll wait for the nxbt update. Thanks for responding though
