### ISSUE TITLE
Errno 107 - Transport endpoint is not connected while running nxbt demo

### ISSUE THREAD

**Issue by Chrisrdouglas** [Brikwerk/nxbt#14]
Hi Brikwerk,

I was testing this out on a Raspberry Pi 4 and got an error during the demo. After running the demo I'm unable to connect to the Switch again until I remove the device from my connection history. Do you have any thoughts on how I might go about fixing it? Is there any information you would like for me to collect?

-Chris

```[2021-02-18 20:22:05,262] ERROR in server: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 145, in mainloop
    itr.sendall(msg)
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 189, in save_connection
    itr, ctrl = self.reconnect(self.switch_address)
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 357, in reconnect
    test_ctrl.connect((reconnect_address, 17))
OSError: [Errno 113] No route to host
[2021-02-18 20:22:05,769] ERROR in server: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 145, in mainloop
    itr.sendall(msg)
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 189, in save_connection
    itr, ctrl = self.reconnect(self.switch_address)
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 357, in reconnect
    test_ctrl.connect((reconnect_address, 17))
OSError: [Errno 113] No route to host```


And here's what happens when I use the webapp
```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 145, in mainloop
    itr.sendall(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 189, in save_connection
    itr, ctrl = self.reconnect(self.switch_address)
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 357, in reconnect
    test_ctrl.connect((reconnect_address, 17))
OSError: [Errno 113] No route to host
[2021-02-18 20:31:57,813] ERROR in server: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 145, in mainloop
    itr.sendall(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 189, in save_connection
    itr, ctrl = self.reconnect(self.switch_address)
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 357, in reconnect
    test_ctrl.connect((reconnect_address, 17))
OSError: [Errno 113] No route to host```

**Comment by Brikwerk** [comment]
Hi Chris, thanks for checking out NXBT. From your error logs, it looks like something is going wrong in the Bluetooth layer of your Raspberry Pi. The initial pairing procedure seems to have succeeded to some extent since NXBT made it to the mainloop, however, the connection is getting dropped after that. My guess is that this is a pairing issue caused by some disagreement or error on link key creation (basically, the process by which your Switch and Pi acknowledge and verify communications with each other).

To get things started, I'll need some more information from you to debug this:
- Linux Info: `uname -a`
- Python 3 Version: `python3 --version`
- Are you using the internal Bluetooth adapter or an external one? Do you have any USB Bluetooth adapters plugged into the Pi?
- Are you using `sudo` to run the demo?
- Do you connect to the Switch while it's on the "Change Grip/Order Menu"?
- Do you have any other Bluetooth products connected to the Pi (eg: Wireless Keyboards, Mice, Headphones, etc)

**Comment by Chrisrdouglas** [comment]
Hey! Happy Friday!

- uname output: ```Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux```
- Python Version: Python 3.7.5
- There are no other bluetooth devices plugged into the Pi
- I ran it using sudo
- I was on the "Change Grip/Order Menu" when I ran the demo
- I have no other bluetooth devices connected to the Pi
- The demo gets into the settings and back to the "Change Grip/Order Menu" then disconnects. Trying to run it a second time is where I run into the issue.

So, I was playing with it this about an hour ago and found out that it will connect using a simple script I made but the demo still wont run a second time unless I remove the Switch from the device history. Since it's only the demo that's not working now I guess it's an insignificant issue because your API is working today. I'm going to guess that the reason why the script I made last night didn't work was because I goofed up somehow.

**Comment by Chrisrdouglas** [comment]
Update: Cant run my scripts without removing the device again :(

**Comment by Brikwerk** [comment]
Alright, your last point changes things. I had forgotten about this (and I should probably list this in the README), however, the demo will spit out some errors when it navigates back to the Change Grip/Order Menu. The Switch kills every Bluetooth controller's connection on that menu and forces them to reconnect from scratch. The errors you're seeing are NXBT realizing its Bluetooth connection has been killed, attempting a fast reconnect which ended in failure, and finally resorting to booting into full reconnection mode (which relies on the Switch to initiate reconnection). This is normal behaviour with the demo and, if left, it should reconnect and then quit.

Still, the demo not running a second time is definitely a problem. Is there a specific error the demo spits out on the second time or does it just never connect on the Change Grip/Order Menu? When you originally ran the demo, did you wait for the demo to exit on its own or did you end it? FYI, I've seen reconnection to the Switch (in rare cases) take up to 15 seconds, so you might need to wait a bit on the Change Grip/Order Menu during the demo.

Finally, would you be able to post an example script that's having trouble on your Pi?

**Comment by Brikwerk** [comment]
Closing due to inactivity. Please comment if you're still having issues.
