### ISSUE TITLE
[Errno 107] Transport endpoint is not connected // [Errno 113] No route to host

### ISSUE THREAD

**Issue by ebisbe** [Brikwerk/nxbt#17]
I got this error. It's from a Pi 3 iirc. 
```
192.168.0.102 - - [06/Apr/2021 22:44:46] "GET /socket.io/?EIO=4&transport=polling&t=NYf9I32&sid=sWegbfCfpW_e5LzcAAAA HTTP/1.1" 200 181 0.000476
Create Controller
[2021-04-06 22:44:49,861] ERROR in server: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 145, in mainloop
    itr.sendall(msg)
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 189, in save_connection
    itr, ctrl = self.reconnect(self.switch_address)
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 357, in reconnect
    test_ctrl.connect((reconnect_address, 17))
OSError: [Errno 113] No route to host
[2021-04-06 22:44:50,373] ERROR in server: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 145, in mainloop
    itr.sendall(msg)
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 189, in save_connection
    itr, ctrl = self.reconnect(self.switch_address)
  File "/usr/local/lib/python3.7/dist-packages/nxbt/controller/server.py", line 357, in reconnect
    test_ctrl.connect((reconnect_address, 17))
OSError: [Errno 113] No route to host
```

I'll try to format the software as I did a lot of weird things in that I have forgotten already... 

By the way. This project seems really interesting.

**Comment by Brikwerk** [comment]
Thanks for your interest in the project!

By any chance, have you updated your Switch recently (within the last week)? Nintendo pushed v12 of SwitchOS which has thrown a wrench into current controller emulation techniques. If you haven't this may be another error, however, I suspect this is likely the issue. If your Switch is on v12, please refer to #18 for progress updates on support.

**Comment by ebisbe** [comment]
@Brikwerk I had issues with a previous project in the Pi1 as well. I'm not even sure it will work at all. My best option is some kind of reset of the operating system maybe...
