### ISSUE TITLE
Use with runit or other systemd alternatives

### ISSUE THREAD

**Issue by MintMellowCat** [Brikwerk/nxbt#25]
I am using Artix Linux with Runit and when I try to start nxbt it comes up with this error:
`Traceback (most recent call last):
  File "/usr/bin/nxbt", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/nxbt/cli.py", line 223, in main
    demo()
  File "/usr/lib/python3.9/site-packages/nxbt/cli.py", line 139, in demo
    nx = Nxbt(debug=args.debug, log_to_file=args.logfile)
  File "/usr/lib/python3.9/site-packages/nxbt/nxbt.py", line 181, in __init__
    toggle_input_plugin(False)
  File "/usr/lib/python3.9/site-packages/nxbt/bluez.py", line 108, in toggle_input_plugin
    with open(service_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lib/systemd/system/bluetooth.service'`
I can't do anything without modifying the code and I don't really want to spend time changing the code. Please could you add support for at least runit. Thanks.

**Comment by dogtopus** [comment]
Worse: It also doesn't respect the systemd's unit file overriding mechanisms and just overwrite the packaged unit files, which could upset some package managers when users update.

**Comment by Brikwerk** [comment]
Apologies for the extended time it's taken me to address this issue. I've implemented some preliminary systemd detection into the BlueZ toggle so that NXBT will at least attempt to run on non-systemd installations (086293d). It would be great to hear if this successfully helps non-systemd users.

One catch with this approach, however, is that the user may have to disable the BlueZ input plugin (or any other interfering plugins) manually. I unfortunately don't have the bandwidth to implement full support for runit/alternatives, at the moment. I would, though, be happy to review a PR implementing further specific support.

**Comment by typenoob** [comment]
I thought it‘s important to add service support in [toggle_clean_bluez](https://github.com/Brikwerk/nxbt/blob/ec4b800ad6c55de96bb6c7f9f84b5bdc59a4c975/nxbt/bluez.py#L96) at least.At present,  , for non-systemd users, temporary approach is to comment all code in this function.

**Comment by typenoob** [comment]
Alright，for openwrt/procd users,here is my advice:
1. Modify file /etc/init.d/bluetoothd
![image](https://github.com/Brikwerk/nxbt/assets/61347081/e1aaa715-d828-42c5-868a-ad70a37e650d)
2. Add file /etc/config/bluetoothd
![image](https://github.com/Brikwerk/nxbt/assets/61347081/d2a6788f-2b66-44bd-a8cb-c34cc854ebe1)
3. exec `uci commit`
4. exec `service bluetoothd restart `

**Comment by typenoob** [comment]
The "default SysV Init" parameter file or directory is variable. You should modify the config file depend on the ditros.
For example,debian users can modify the file /etc/default/bluetooth

![image](https://github.com/Brikwerk/nxbt/assets/61347081/0f7a2298-4fd9-4b2b-b232-b3afe96bb35b)
