### ISSUE TITLE
Controller disconnect after running a macro

### ISSUE THREAD

**Issue by wecarrasco** [Brikwerk/nxbt#46]
Hello! 

On the webapp (windows), always after finishing a macro the controller disconnects and I need to press the "Recreate Controller" button in order to run a new macro.

This is the error I receive on the terminal:

`10.0.2.2 - - [09/Dec/2021 15:36:49] "POST /socket.io/?EIO=4&transport=polling&t=NsVrmS1&sid=dVb7FWinR3o8ydzuAACI HTTP/1.1" 200 219 0.001366
post request handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 431, in handle_request
    socket.handle_post_request(environ)
  File "/usr/local/lib/python3.8/dist-packages/engineio/socket.py", line 124, in handle_post_request
    p = payload.Payload(encoded_payload=body)
  File "/usr/local/lib/python3.8/dist-packages/engineio/payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "/usr/local/lib/python3.8/dist-packages/engineio/payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload`

Is there a way I can prevent it to disconnect or a way to autmatically reconnect the controller?

**Comment by RwbyChan** [comment]
It seems to disconnect here too, but seems like there is no error:
Create Controller
```
10.0.2.2 - - [17/Dec/2021 20:50:56] "GET /socket.io/?EIO=4&transport=polling&t=NtAANWw HTTP/1.1" 200 278 0.004319
10.0.2.2 - - [17/Dec/2021 20:50:56] "GET /socket.io/?EIO=4&transport=polling&t=NtAAHvX HTTP/1.1" 200 278 0.00423410.0.2.2 - - [17/Dec/2021 20:50:56] "POST /socket.io/?EIO=4&transport=polling&t=NtAAOGB&sid=wfBH8qzXEb814a3bAAAX HTTP/1.1" 200 219 0.003689
(1400) accepted ('10.0.2.2', 54947)
10.0.2.2 - - [17/Dec/2021 20:50:56] "GET /socket.io/?EIO=4&transport=polling&t=NtAAOGD&sid=wfBH8qzXEb814a3bAAAX HTTP/1.1" 200 213 0.000311
10.0.2.2 - - [17/Dec/2021 20:50:56] "GET /socket.io/?EIO=4&transport=polling&t=NtAAOGU&sid=wfBH8qzXEb814a3bAAAX HTTP/1.1" 200 181 0.000180
10.0.2.2 - - [17/Dec/2021 20:50:56] "POST /socket.io/?EIO=4&transport=polling&t=NtAAOGT&sid=wfBH8qzXEb814a3bAAAX HTTP/1.1" 200 219 0.014735
Disconnected
10.0.2.2 - - [17/Dec/2021 20:50:56] "GET /socket.io/?EIO=4&transport=websocket&sid=YzMa6J338Twl50JmAAAV HTTP/1.1" 200 0 252.563556
```

**Comment by G-Rex2595** [comment]
Until this gets actually fixed, you could try something like this.
```
let statusIndicator = document.getElementById('status-indicator-text');
function watchForDisconnect() {
  let intervalId = window.setInterval(() => {
    if(statusIndicator.innerText !== 'CONNECTED') {
      restartController();
      watchForReconnect();
      window.clearInterval(intervalId);
    }, 100);
}
function watchForReconnect() {
  let intervalId = window.setInterval(() => {
    if(statusIndicator.innerText === 'CONNECTED') {
      watchForDisconnect();
      window.clearInterval(intervalId);
    }
  }, 100);
}
```
Or you can try what I'm currently doing.
```
let statusIndicator = document.getElementById('status-indicator-text');
function restartAndRunMacro() {
	restartController();
	let intervalId = window.setInterval(() => {
		if(statusIndicator.innerText === 'CONNECTED') {
			window.clearInterval(intervalId);
			sendMacro();
		}
	}, 100)
}
```

## Less Techy People:
If you don't know how to run those, just F12 and go to the console tab and paste the code. Also, don't run code random people on the internet give you unless you know what the code does. I'm not going to explain this code to you. If you don't understand it, you shouldn't run it, even if I tell you exactly what it does.
