### ISSUE TITLE
Controller disconnects after closing the "Change Grip/Order" menu

### ISSUE THREAD

**Issue by jollaWellbuur** [Brikwerk/nxbt#5]
I tried to get nxbt working on Manjaro Linux using sudo pip install nxbt. Install runs successful. However, when I run the demo and go to the "Change Grip/Order" menu, the controller instantly disconnects after first connecting. 

The tui connects, but also disconnects after closing the menu. The webapp does not connect at all.

Any ideas?
Here is the error code:

```
[2020-12-22 15:32:18,026] ERROR in server: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nxbt/controller/server.py", line 145, in mainloop
    itr.sendall(msg)
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nxbt/controller/server.py", line 189, in save_connection
    itr, ctrl = self.reconnect(self.switch_address)
  File "/usr/lib/python3.8/site-packages/nxbt/controller/server.py", line 357, in reconnect
    test_ctrl.connect((reconnect_address, 17))
OSError: [Errno 113] No route to host

```

edit: After some more fiddling, I got to connect the controller in demo and tui-mode, IF another controller is connected as first controller. Delay is insanely long, though.

**Comment by Brikwerk** [comment]
Hi @jollaWellbuur and thanks for your interest in nxbt. This is a rather interesting issue.

What your error log is telling me is that the connection process was successful, interrupt/control sockets were obtained, and packets were exchanged. The connection seems to be getting dropped when the input frequency (15Hz on the Change Grip/Order Menu) is increased to the full 120Hz. Unfortunately, I'm not able to reproduce the error/behaviour you've mentioned from some initial testing on my own Manjaro 20.1 installation, however, there might be something I've missed.

To get the ball rolling on solving this issue for you, I've got a few questions:
- Which version of Manjaro are you using? You should be able to get this info by running `cat /etc/lsb-release`.
- Are you using an external Bluetooth dongle for Bluetooth capability? If so, how old is this dongle?
- Do you use any Bluetooth peripherals with the PC you're using nxbt on? Eg: Bluetooth Headphones, Keyboards, Mice, etc.
- In your edit, you mention some delay is occurring? Is this in the order of milliseconds or seconds? Does the delay increase with time?
- Does nxbt's reconnect functionality work without another controller connected? Eg: With your Switch on the home menu, are you able to run `sudo nxbt tui -r` and a successful connection is made?

**Comment by jollaWellbuur** [comment]
Hi, thanks for your reply. To answer your questions:

- Manjaro Version: 
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.2
DISTRIB_CODENAME=Nibia
DISTRIB_DESCRIPTION="Manjaro Linux"
```
- Internal Bluetooth (ThinkPad from 2017)
- I do not use other peripherals paralel to nxbt, but have used bluetooth peripherals in the past without issue.
- The delay is about one second. It does not appear to increase with time.
- Reconnection is not possible.

After some more testing I was able to establish a connection using [switchremoteserver](https://github.com/juharris/switch-remoteplay/tree/main/server). The problems are the same, however; I am disconnected after leaving the grip order menu.

**Comment by Brikwerk** [comment]
Thanks for answering my questions. Your point regarding Switch Remote Server is specifically intriguing since that utility uses a different controller emulation backend than nxbt. Since you're encountering a similar issue while using both utilities, I think we might be dealing with a problem slightly lower in the stack or possibly something hardware related.

Since your machine seems happy during the connection phase of emulation, I've created a new branch on the repo that maintains the connection phase's 15Hz frequency throughout the entire emulation process. If possible, would you be able to test this branch? I'll outline some instructions below on how to clone/install a working copy of the branch.

1. Clone the repo into a location of your choice: `git clone https://github.com/Brikwerk/nxbt`
2. Uninstall the pypi version of nxbt: `sudo pip3 uninstall nxbt`
3. Navigate inside the cloned repo and checkout the new branch: `git checkout frequency-test`
4. Install the local variant of nxbt: `sudo pip3 install -e .`
5. Try to connect to your Switch again on the Change Grip/Order Menu: `sudo nxbt tui` or `sudo nxbt demo` (keep in mind the demo may not work perfectly since the refresh rate is quite a bit lower with this branch).
6. To uninstall the local version of nxbt, run `sudo rm -rf nxbt.egg-info` at the root of the cloned repo

Let me know if this helps with the dropped connection after navigating off of the Change Grip/Order Menu.

**Comment by Brikwerk** [comment]
Closing issue due to lack of activity.
