### ISSUE TITLE
TUI Fails while WebApp works

### ISSUE THREAD

**Issue by ayunami2000** [Brikwerk/nxbt#58]
The webapp works, but the TUI connects for about 1-2 seconds then says "Crashed" and closes. "Software caused connection abort" "Connection reset by peer" But the weird thing is that the webapp still works just fine. By the way I am using the command `sudo nxbt tui -r` on a raspberry pi 3 (I think its the 3, but it shouldnt matter) I installed it using pip3. If you need the full copypaste error log let me know.

**Comment by luo1ding** [comment]
I am experiencing this issue as well. I do have a solution so far, which is disconnect all the controller in your switch (setting-controller-at bottom-disconnect), then start the `sudo nxbt tui` to create a new controller and then connect. This will allow your tui to work once.

**Comment by pllopis** [comment]
I'm having the same issue. When started with `nxbt -r tui` and the switch is in the Change Grip/Order menu, it successfully connects and after 1s it crashes:

```
Traceback (most recent call last):
  File "/home/pllopis/src/nxbt-test/env/bin/nxbt", line 8, in <module>
    sys.exit(main())
  File "/home/pllopis/src/nxbt-test/env/lib/python3.9/site-packages/nxbt/cli.py", line 331, in main
    tui.start()
  File "/home/pllopis/src/nxbt-test/env/lib/python3.9/site-packages/nxbt/tui.py", line 323, in start
    self.mainloop(self.term)
  File "/home/pllopis/src/nxbt-test/env/lib/python3.9/site-packages/nxbt/tui.py", line 383, in mainloop
    self.remote_input_loop(term)
  File "/home/pllopis/src/nxbt-test/env/lib/python3.9/site-packages/nxbt/tui.py", line 441, in remote_input_loop
    self.check_for_disconnect(term)
  File "/home/pllopis/src/nxbt-test/env/lib/python3.9/site-packages/nxbt/tui.py", line 629, in check_for_disconnect
    raise ConnectionError(errors)
ConnectionError: Traceback (most recent call last):
  File "/home/pllopis/src/nxbt-test/env/lib/python3.9/site-packages/nxbt/controller/server.py", line 106, in run
    self.mainloop(itr, ctrl)
  File "/home/pllopis/src/nxbt-test/env/lib/python3.9/site-packages/nxbt/controller/server.py", line 128, in mainloop
    reply = itr.recv(50)
ConnectionAbortedError: [Errno 103] Software caused connection abort
```

The fix mentioned of restarting bluetooth and creating a new controller to connect with `nxbt tui` worked once for me, but I can't reproduce it anymore, so also seems inconsistent. Webapp is generally working better for me though.
I'm using a Raspberry model rpi4, and the Switch is on version 16.0.3.
