### ISSUE TITLE
Webapp dont work

### ISSUE THREAD

**Issue by Diee92** [Brikwerk/nxbt#61]
hello, first thanks for the program, I have a problem with the webapp, I installed it in windows, everything is working but when I want to start the page it shows me this error

Traceback (most recent call last):
  File "/usr/local/bin/nxbt", line 33, in <module>
    sys.exit(load_entry_point('nxbt', 'console_scripts', 'nxbt')())
  File "/vagrant/nxbt/cli.py", line 321, in main
    from .web import start_web_app
  File "/vagrant/nxbt/web/__init__.py", line 1, in <module>
    from .app import start_web_app
  File "/vagrant/nxbt/web/app.py", line 9, in <module>
    from flask import Flask, render_template, request
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/dist-packages/itsdangerous/__init__.py)

any ideas? Thank you

**Comment by Uniersr** [comment]
The only workaround for nxbt to work is by downgrading Flash to version 1.0.3 then remove the "from itsdangerous" from line 15 in the file "/usr/local/lib/python3.8/dist-packages/flask/json/init.py", that's it.
![431](https://user-images.githubusercontent.com/99698024/155640115-070e0215-6a9e-41ea-befa-6b943add67e7.PNG)
![432](https://user-images.githubusercontent.com/99698024/155640138-ac31b651-84b5-4a78-90c4-927b27e518c1.PNG)

**Comment by Diee92** [comment]
it worked! Thanks a lot

**Comment by blastkool** [comment]
How exactly do I get to that file? I don't see it in my Python directory.

**Comment by amberestelle** [comment]
Similar issue:

Traceback (most recent call last):
  File "/usr/local/bin/nxbt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/nxbt/cli.py", line 321, in main
    from .web import start_web_app
  File "/usr/local/lib/python3.8/dist-packages/nxbt/web/__init__.py", line 1, in <module>
    from .app import start_web_app
  File "/usr/local/lib/python3.8/dist-packages/nxbt/web/app.py", line 9, in <module>
    from flask import Flask, render_template, request
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)

any ideas?

**Comment by l4desu-mizu** [comment]
I'd like to try updating the dependencies. from what I see they are about a year old with some libs had major upgrades which introduce breaking changes. also, from what ive seen some code (i think dependency code) would not run with python3.8 or later.

**Comment by Uniersr** [comment]
[amberestelle](https://github.com/amberestelle) said:
> any ideas?

Ok, i'll try to find the........ (looking at i4desu-mizu's post before i could say "workarounds.")
> I'd like to try updating the dependencies.

Well, i was too late then, better luck next time for me...... ¯\_(ツ)_/¯

**Comment by jiyarong** [comment]
same error here, any ideas?

**Comment by l4desu-mizu** [comment]
> same error here, any ideas?

although I should try updating the dependencies yet again, you could try the branch that I've linked (not tested for a while)

**Comment by tea-bone2000** [comment]
I tried doing all of this today and am still getting the "ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/init.py)" when trying to launch the webapp

**Comment by glatavento** [comment]
I found [this fork](https://github.com/piratasdoraio/nxbt) from [useful-forks](https://useful-forks.github.io/?repo=Brikwerk%2Fnxbt) and luckily it works. Just create a venv, activate it, and run below to install it.
```bash
pip install git+https://github.com/piratasdoraio/nxbt.git
```
