### ISSUE TITLE
Bluetooth being soft block after running the demo or tui.

### ISSUE THREAD

**Issue by RoboticUnit44313E** [Brikwerk/nxbt#70]
Hello, thanks for the program, but I encountered an issue that seems to appear after I upgraded my switch system to 14.1.1.

After running `sudo nxbt demo` command, I got the error below:
`An error occurred while running the demo:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nxbt/controller/server.py", line 96, in run
    itr, ctrl = self.connect()
  File "/usr/local/lib/python3.8/dist-packages/nxbt/controller/server.py", line 371, in connect
    self.bt.set_discoverable(True)
  File "/usr/local/lib/python3.8/dist-packages/nxbt/bluez.py", line 549, in set_discoverable
    self.device.Set(ADAPTER_INTERFACE, "Discoverable", dbus_value)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.bluez.Error.Failed: Not Powered`

After running the command again, the terminal suggested that Bluetooth was being blocked:
`An error occurred while running the demo:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nxbt/controller/server.py", line 88, in run
    self.controller.setup()
  File "/usr/local/lib/python3.8/dist-packages/nxbt/controller/controller.py", line 43, in setup
    self.bt.set_powered(True)
  File "/usr/local/lib/python3.8/dist-packages/nxbt/bluez.py", line 646, in set_powered
    self.device.Set(ADAPTER_INTERFACE, "Powered", dbus_value)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.bluez.Error.Blocked: Blocked through rfkill`

I tried to unblock the Bluetooth in rfkill list, but it will be blocked again if I run the demo or tui.

**Comment by logbaseaofn** [comment]
Have you turned bluetooth on?

**Comment by RoboticUnit44313E** [comment]
> Have you turned Bluetooth on?

The Bluetooth was powered on and can detect devices normally, but it will be constantly turned off and on until the terminal throws an error.
