### ISSUE TITLE
webapp error

### ISSUE THREAD

**Issue by printerpenguin** [Brikwerk/nxbt#75]
when i try to run "nxbt webapp" i get 'ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' " (Traceback (most recent call last):
  File "/usr/local/bin/nxbt", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/nxbt/cli.py", line 321, in main
    from .web import start_web_app
  File "/usr/local/lib/python3.7/dist-packages/nxbt/web/__init__.py", line 1, in <module>
    from .app import start_web_app
  File "/usr/local/lib/python3.7/dist-packages/nxbt/web/app.py", line 9, in <module>
    from flask import Flask, render_template, request
  File "/usr/local/lib/python3.7/dist-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 32, in <module>
    from werkzeug.wrappers import BaseResponse
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (/usr/local/lib/python3.7/dist-packages/werkzeug/wrappers/__init__.py))

**Comment by printerpenguin** [comment]
this is after i tried to fix the jinja2 escape error, and downgrading werkzeug prompts the jinja 2 escape error to appear again

**Comment by printerpenguin** [comment]
never mind, just had to install the downgrades with sudo commands

**Comment by justincys** [comment]
Hi, could you give instructions on how to do this?

My error is a little different, but maybe your steps can help me.
```
Traceback (most recent call last):
  File "/usr/local/bin/nxbt", line 33, in <module>
    sys.exit(load_entry_point('nxbt', 'console_scripts', 'nxbt')())
  File "/vagrant/nxbt/cli.py", line 321, in main
    from .web import start_web_app
  File "/vagrant/nxbt/web/__init__.py", line 1, in <module>
    from .app import start_web_app
  File "/vagrant/nxbt/web/app.py", line 9, in <module>
    from flask import Flask, render_template, request
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)
```

**Comment by justincys** [comment]
Thank you. I tried each line but I keep getting the same error with a different package name and version.
`install: missing destination file operand after 'jinja2==3.0.3'`

**Comment by printerpenguin** [comment]
maybye try sudo apt-get install jinja2==3.0.3?

**Comment by l4desu-mizu** [comment]
related to #61 ?

**Comment by justincys** [comment]
> duplicate of/related to #61 ?

Thank you, this works great. Replaced the three files in your [pull request](https://github.com/Brikwerk/nxbt/pull/67/files) and having no issues connecting now.

> maybe try sudo apt-get install jinja2==3.0.3?

Tried it too, didn't work. Forgot to report back here but thank you for trying to help.

**Comment by nasapierce** [comment]
fixed these error by downgrading:
jinja2 to 3.0.3
itsdangerous to 2.0.1
werkzeug to 2.0.3

`sudo pip3 install jinja2==3.0.3`
`sudo pip3 install itsdangerous==2.0.1`
`sudo pip3 install jinja2==2.0.3`
