### ISSUE TITLE
Issues running macros through .txt file

### ISSUE THREAD

**Issue by HappyJuiceLive** [Brikwerk/nxbt#77]
`Controller crashed while running macro
Traceback (most recent call last):
  File "/vagrant/nxbt/controller/server.py", line 106, in run
    self.mainloop(itr, ctrl)
  File "/vagrant/nxbt/controller/server.py", line 155, in mainloop
    self.input.set_protocol_input(state=self.state)
  File "/vagrant/nxbt/controller/input.py", line 202, in set_protocol_input
    self.macro_timer_length = float(timer_length)
ValueError: could not convert string to float: 'macro.tx'`

is what I get, regardless of what I say the name of the macro.txt file is. Will just return the same thing "...ValueError: could not convert string to float: 'bbaerbaetusrthaegasdh'"

Seems to suggest that it's unable to locate the file, any suggestions?

**Comment by Bien-CV** [comment]
You seem to be using a variable named timer_length to store your macro, please don't, it should be a number.
