### ISSUE TITLE
can't install it using the pip3 command

### ISSUE THREAD

**Issue by lomorster** [Brikwerk/nxbt#87]
When ever I try to install it it gives me the error it couldnt install the dbus-python package
Does anyone know how to solve this?(it doesnt work without the package)
OS : Ubuntu 22.04 LTS

here is the error reported from console
Building wheels for collected packages: dbus-python
  Building wheel for dbus-python (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [162 lines of output]
      running bdist_wheel
      running build
      creating /tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/build
      creating /tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/build/temp.linux-x86_64-3.10
      checking whether make supports nested variables... yes
      checking whether to enable maintainer-specific portions of Makefiles... no
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to accept ISO C89... none needed
      checking whether gcc understands -c and -o together... yes
      checking how to run the C preprocessor... gcc -E
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking minix/config.h usability... no
      checking minix/config.h presence... no
      checking for minix/config.h... no
      checking whether it is safe to define __EXTENSIONS__... yes
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
      checking for gawk... no
      checking for mawk... mawk
      checking whether make sets $(MAKE)... yes
      checking whether make supports the include directive... yes (GNU style)
      checking whether UID '1000' is supported by ustar format... yes
      checking whether GID '1000' is supported by ustar format... yes
      checking how to create a ustar tar archive... gnutar
      checking dependency style of gcc... gcc3
      checking build system type... x86_64-pc-linux-gnu
      checking host system type... x86_64-pc-linux-gnu
      checking for native Windows host... no
      checking how to print strings... printf
      checking for a sed that does not truncate output... /usr/bin/sed
      checking for fgrep... /usr/bin/grep -F
      checking for ld used by gcc... /usr/bin/ld
      checking if the linker (/usr/bin/ld) is GNU ld... yes
      checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
      checking the name lister (/usr/bin/nm -B) interface... BSD nm
      checking whether ln -s works... yes
      checking the maximum length of command line arguments... 1572864
      checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
      checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
      checking for /usr/bin/ld option to reload object files... -r
      checking for objdump... objdump
      checking how to recognize dependent libraries... pass_all
      checking for dlltool... no
      checking how to associate runtime and link libraries... printf %s\n
      checking for ar... ar
      checking for archiver @FILE support... @
      checking for strip... strip
      checking for ranlib... ranlib
      checking command to parse /usr/bin/nm -B output from gcc object... ok
      checking for sysroot... no
      checking for a working dd... /usr/bin/dd
      checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
      checking for mt... mt
      checking if mt is a manifest tool... no
      checking for dlfcn.h... yes
      checking for objdir... .libs
      checking if gcc supports -fno-rtti -fno-exceptions... no
      checking for gcc option to produce PIC... -fPIC -DPIC
      checking if gcc PIC flag -fPIC -DPIC works... yes
      checking if gcc static flag -static works... yes
      checking if gcc supports -c -o file.o... yes
      checking if gcc supports -c -o file.o... (cached) yes
      checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
      checking whether -lc should be explicitly linked in... no
      checking dynamic linker characteristics... GNU/Linux ld.so
      checking how to hardcode library paths into programs... immediate
      checking whether stripping libraries is possible... yes
      checking if libtool supports shared libraries... yes
      checking whether to build shared libraries... yes
      checking whether to build static libraries... no
      checking for inline... inline
      checking for gawk... (cached) mawk
      checking for python... /usr/bin/python3
      checking for a version of Python >= '2.1.0'... yes
      checking for a version of Python >= '2.7'... yes
      checking for the distutils Python package... yes
      checking for Python include path... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -I/usr/include/python3.10
      checking for Python library path... <stdin>:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <stdin>:4: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      <stdin>:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <stdin>:3: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      <stdin>:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <stdin>:2: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -L/usr/lib/x86_64-linux-gnu -lpython3.10
      checking for Python site-packages path... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      /usr/lib/python3/dist-packages
      checking python extra libraries... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -lcrypt -ldl  -lm -lm
      checking python extra linking flags... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
      checking consistency of all components of python development environment... yes
      checking for python version... 3.1
      checking for python platform... linux
      checking for python script directory... ${prefix}/local/lib/python3.10/dist-packages
      checking for python extension module directory... ${exec_prefix}/local/lib/python3.10/dist-packages
      <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      checking python3 module: sphinx... no
      checking python3 module: sphinx_rtd_theme... no
      checking for dbus-run-session... /usr/bin/dbus-run-session
      checking for pkg-config... no
      checking for DBUS... no
      configure: error: in `/tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/build/temp.linux-x86_64-3.10':
      configure: error: The pkg-config script could not be found or is too old.  Make sure it
      is in your PATH or set the PKG_CONFIG environment variable to the full
      path to pkg-config.
      
      Alternatively, you may set the environment variables DBUS_CFLAGS
      and DBUS_LIBS to avoid the need to call pkg-config.
      See the pkg-config man page for more details.
      
      To get pkg-config, see <http://pkg-config.freedesktop.org/>.
      See `config.log' for more details
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/setup.py", line 85, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/setup.py", line 56, in run
          subprocess.check_call([
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/build/temp.linux-x86_64-3.10/prefix']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
Failed to build dbus-python
Installing collected packages: dbus-python, python-xlib, python-engineio, pycparser, psutil, MarkupSafe, itsdangerous, greenlet, dnspython, blessed, bidict, Werkzeug, python-socketio, pynput, Jinja2, eventlet, cffi, Flask, cryptography, Flask-SocketIO, nxbt
  Running setup.py install for dbus-python ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for dbus-python did not run successfully.
  │ exit code: 1
  ╰─> [166 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      creating /tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/build
      creating /tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/build/temp.linux-x86_64-3.10
      checking whether make supports nested variables... yes
      checking whether to enable maintainer-specific portions of Makefiles... no
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to accept ISO C89... none needed
      checking whether gcc understands -c and -o together... yes
      checking how to run the C preprocessor... gcc -E
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking minix/config.h usability... no
      checking minix/config.h presence... no
      checking for minix/config.h... no
      checking whether it is safe to define __EXTENSIONS__... yes
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
      checking for gawk... no
      checking for mawk... mawk
      checking whether make sets $(MAKE)... yes
      checking whether make supports the include directive... yes (GNU style)
      checking whether UID '1000' is supported by ustar format... yes
      checking whether GID '1000' is supported by ustar format... yes
      checking how to create a ustar tar archive... gnutar
      checking dependency style of gcc... gcc3
      checking build system type... x86_64-pc-linux-gnu
      checking host system type... x86_64-pc-linux-gnu
      checking for native Windows host... no
      checking how to print strings... printf
      checking for a sed that does not truncate output... /usr/bin/sed
      checking for fgrep... /usr/bin/grep -F
      checking for ld used by gcc... /usr/bin/ld
      checking if the linker (/usr/bin/ld) is GNU ld... yes
      checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
      checking the name lister (/usr/bin/nm -B) interface... BSD nm
      checking whether ln -s works... yes
      checking the maximum length of command line arguments... 1572864
      checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
      checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
      checking for /usr/bin/ld option to reload object files... -r
      checking for objdump... objdump
      checking how to recognize dependent libraries... pass_all
      checking for dlltool... no
      checking how to associate runtime and link libraries... printf %s\n
      checking for ar... ar
      checking for archiver @FILE support... @
      checking for strip... strip
      checking for ranlib... ranlib
      checking command to parse /usr/bin/nm -B output from gcc object... ok
      checking for sysroot... no
      checking for a working dd... /usr/bin/dd
      checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
      checking for mt... mt
      checking if mt is a manifest tool... no
      checking for dlfcn.h... yes
      checking for objdir... .libs
      checking if gcc supports -fno-rtti -fno-exceptions... no
      checking for gcc option to produce PIC... -fPIC -DPIC
      checking if gcc PIC flag -fPIC -DPIC works... yes
      checking if gcc static flag -static works... yes
      checking if gcc supports -c -o file.o... yes
      checking if gcc supports -c -o file.o... (cached) yes
      checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
      checking whether -lc should be explicitly linked in... no
      checking dynamic linker characteristics... GNU/Linux ld.so
      checking how to hardcode library paths into programs... immediate
      checking whether stripping libraries is possible... yes
      checking if libtool supports shared libraries... yes
      checking whether to build shared libraries... yes
      checking whether to build static libraries... no
      checking for inline... inline
      checking for gawk... (cached) mawk
      checking for python... /usr/bin/python3
      checking for a version of Python >= '2.1.0'... yes
      checking for a version of Python >= '2.7'... yes
      checking for the distutils Python package... yes
      checking for Python include path... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -I/usr/include/python3.10
      checking for Python library path... <stdin>:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <stdin>:4: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      <stdin>:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <stdin>:3: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      <stdin>:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <stdin>:2: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -L/usr/lib/x86_64-linux-gnu -lpython3.10
      checking for Python site-packages path... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      /usr/lib/python3/dist-packages
      checking python extra libraries... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -lcrypt -ldl  -lm -lm
      checking python extra linking flags... <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
      -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
      checking consistency of all components of python development environment... yes
      checking for python version... 3.1
      checking for python platform... linux
      checking for python script directory... ${prefix}/local/lib/python3.10/dist-packages
      checking for python extension module directory... ${exec_prefix}/local/lib/python3.10/dist-packages
      <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      checking python3 module: sphinx... no
      checking python3 module: sphinx_rtd_theme... no
      checking for dbus-run-session... /usr/bin/dbus-run-session
      checking for pkg-config... no
      checking for DBUS... no
      configure: error: in `/tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/build/temp.linux-x86_64-3.10':
      configure: error: The pkg-config script could not be found or is too old.  Make sure it
      is in your PATH or set the PKG_CONFIG environment variable to the full
      path to pkg-config.
      
      Alternatively, you may set the environment variables DBUS_CFLAGS
      and DBUS_LIBS to avoid the need to call pkg-config.
      See the pkg-config man page for more details.
      
      To get pkg-config, see <http://pkg-config.freedesktop.org/>.
      See `config.log' for more details
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/setup.py", line 85, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/lib/python3.10/distutils/command/install.py", line 619, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/setup.py", line 56, in run
          subprocess.check_call([
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-install-8mirhvke/dbus-python_caa408028e714b5ca40f9ca98c92d913/build/temp.linux-x86_64-3.10/prefix']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dbus-python

**Comment by cranone** [comment]
> configure: error: The pkg-config script could not be found or is too old. Make sure it

`sudo apt-get install pkg-config` its work for me
and maybe you will have some other error like
> configure: error: Package requirements (dbus-1 >= 1.0) were not met:  

do this: `sudo apt-get install libdbus-glib-1-dev`

**Comment by YiZhiRikka** [comment]
> > configure: error: The pkg-config script could not be found or is too old. Make sure it
> 
> `sudo apt-get install pkg-config` its work for me and maybe you will have some other error like
> 
> > configure: error: Package requirements (dbus-1 >= 1.0) were not met:
> 
> do this: `sudo apt-get install libdbus-glib-1-dev`

It's useful! Thanks!

**Comment by StonedModder** [comment]
For anyone else finding this thread on google years later. I wrote a tutorial to get around this error

https://gbatemp.net/threads/how-to-install-and-use-nxbt.676535/#post-10755222
