### ISSUE TITLE
Controller crashes when trying to run a macro.

### ISSUE THREAD

**Issue by Apollo59** [Brikwerk/nxbt#88]
The script im trying to run is 
DPAD_DOWN 0.1
0.1
DPAD_DOWN 0.1
0.1
DPAD_DOWN 0.1
0.1
A 0.1
2
X 0.1
0.1
A 0.1
2
X 0.1
DPAD_RIGHT 0.1
0.1
DPAD_RIGHT 0.1
0.1
A 0.1
0.1
but it tries to leave and the menu then it says it crashes

Error log is
Controller crashed while running macro
Traceback (most recent call last):
    File "/usr/local/lib/python3.8/dist-packages/nxbt/controller/server.py", line 106, in run
        self.mainloop(itr, ctrl)
    File "/usr/local/lib/python3.8/dist-packages/nxbt/controller/server.py", line 155, in mainloop
        self.input.set_protocol_input(state=self.state)
    File "/usr/local/lib/python3.8/dist-packages/nxbt/controller/input.py", line 202, in set_protocol_input
        self.macro_timer_length = float((timer_length)
ValueError: could not convert string to float: ' '

**Comment by blackcatsnow** [comment]
I am having this exact issue. Were you able to find a solution?

**Comment by blackcatsnow** [comment]
Update:
I have found that nearly everytime I get this error my macro has bad syntax or I am not in the right directory. In the example you posted about I notices that you did not indicate what time interval you are using. Like you used 0.1 instead of 0.1S (S for seconds). I went back through my macros and fixed an error and I don't get this error anymore. I hope this helps you.
