### ISSUE TITLE
Failed to activate service 'org.bluez'

### ISSUE THREAD

**Issue by v1ra1** [Brikwerk/nxbt#91]
`Traceback (most recent call last):
  File "/usr/local/bin/nxbt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/nxbt/cli.py", line 325, in main
    demo()
  File "/usr/local/lib/python3.8/dist-packages/nxbt/cli.py", line 152, in demo
    adapters = nx.get_available_adapters()
  File "/usr/local/lib/python3.8/dist-packages/nxbt/nxbt.py", line 645, in get_available_adapters
    adapters = find_objects(bus, SERVICE_NAME, ADAPTER_INTERFACE)
  File "/usr/local/lib/python3.8/dist-packages/nxbt/bluez.py", line 78, in find_objects
    bus.get_object(service_name, "/"),
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)`

Has anyone ran into this situation?

**Comment by v1ra1** [comment]
![image](https://user-images.githubusercontent.com/8594476/205021216-3945f927-ed45-4a5a-8bd0-000e9792e253.png)

Not sure if the bluetooth service needs to be running. Anytime I try and start it this is the result.

I did however run these commands and it then the bluetooth service was able to start up

sudo rmmod btusb
sleep 1
sudo modprobe btusb

But then nxtb just stops working and says it cannot find any bluetooth adapter

**Comment by v1ra1** [comment]
The solution was unplugging the bluetooth usb and then back in.
