### ISSUE TITLE
How to use Python api, what command to use?

### ISSUE THREAD

**Issue by jiyarong** [Brikwerk/nxbt#96]
-c what is use text string for args
What if I want write a python script, what command to use
like 
```
nxbt -c my_script.py -r
```

?

**Comment by ryu-0729** [comment]
@jiyarong 
Sorry if my English is poor.
I was able to confirm the operation with the following command.
`sudo python my_script.py`

**Comment by git5552** [comment]
Why can't I debug on Pycharm?，and starting run gives me an error >_<    >_<
Traceback (most recent call last):
  File "/home/user/PycharmProjects/pythonProject/1.py", line 63, in <module>
    nx = nxbt.Nxbt()
  File "/home/user/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/nxbt/nxbt.py", line 181, in __init__
    toggle_clean_bluez(True)
  File "/home/user/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/nxbt/bluez.py", line 121, in toggle_clean_bluez
    with open(service_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lib/systemd/system/bluetooth.service' >_<

Forgive me for being a novice.   >_<
